export enum PERMISSION {
  // Admin
  ADMIN_ADD = "ADMIN_ADD",
  ADMIN_VIEW = "ADMIN_VIEW",
  ADMIN_EDIT = "ADMIN_EDIT",
  ADMIN_DELETE = "ADMIN_DELETE",
  USER_ADD = "USER_ADD",
  USER_VIEW = "USER_VIEW",
  USER_EDIT = "USER_EDIT",
  USER_DELETE = "USER_DELETE",
  ROLE_ADD = "ROLE_ADD",
  ROLE_VIEW = "ROLE_VIEW",
  ROLE_EDIT = "ROLE_EDIT",
  ROLE_DELETE = "ROLE_DELETE",
  RESOURCE_ADD = "RESOURCE_ADD",
  RESOURCE_VIEW = "RESOURCE_VIEW",
  RESOURCE_EDIT = "RESOURCE_EDIT",
  RESOURCE_DELETE = "RESOURCE_DELETE",

  // Dashboard
  DASHBOARD_ADD = "DASHBOARD_ADD",
  DASHBOARD_VIEW = "DASHBOARD_VIEW",
  DASHBOARD_EDIT = "DASHBOARD_EDIT",
  DASHBOARD_DELETE = "DASHBOARD_DELETE",

  INFRASTRUCTURE_ADD = "INFRASTRUCTURE_ADD",
  INFRASTRUCTURE_VIEW = "INFRASTRUCTURE_VIEW",
  INFRASTRUCTURE_EDIT = "INFRASTRUCTURE_EDIT",
  INFRASTRUCTURE_DELETE = "INFRASTRUCTURE_DELETE",
}
